server:
  address: ":8000"
  readTimeout: "30s"
  writeTimeout: "30s"
  shutdownTimeout: "10s"
  cors:
    allowOrigins:
      - "http://*"
      - "https://*"
    allowMethods: [ "OPTIONS", "HEAD", "POST", "GET", "PATCH", "DELETE" ]
    allowHeaders:
      - Content-Type
      - Accept
      - Accept-Language
      - Authorization
      - X-Request-Id
  responseLogLimitByte: 10000
  uploadSizeLimitByte: 5242880
  token:
    jwtSecretKey: "abc123"
    timeToExpired: "6000s"

postgres:
  host: localhost
  port: 5432
  database: namdb
  user: user
  password: password

smartContract:
  host: "http://127.0.0.1:8545"
  contractAddress: "0x24eF67C1a1b18F9F8D07999d39D8De9bA3BAE1Db"
  privateKey: "894743a6336cd65127f3131d30b7d3d83a06fa7d9b7ac83eca38375d1bc8655e"
  chanID: 1337
